version: '3'

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    command: ["/bin/sh", "-c", "redis-server --requirepass password"]
    volumes:
      - redis_data:/data

  chatwoot:
    image: chatwoot/chatwoot:latest
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - 3031:3000
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=chatwoot_production
      - REDIS_URL=redis://:password@redis:6379
      - SECRET_KEY_BASE=replace_with_your_super_duper_secret_key_base
      - FRONTEND_URL=http://localhost:3031
      - DEFAULT_LOCALE=en
      - ENABLE_ACCOUNT_SIGNUP=true
      - FORCE_SSL=false
    entrypoint: docker/entrypoints/rails.sh
    command: bundle exec rails s -p 3000 -b 0.0.0.0

volumes:
  postgres_data:
  redis_data:
