version: '3'

services:
  postgres:
    image: ankane/pgvector:latest
    restart: always
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chatwoot-network

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - chatwoot-network

  chatwoot:
    image: chatwoot/chatwoot:latest
    depends_on:
      - postgres
      - redis
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=abcd1234
      - FRONTEND_URL=http://localhost:3031
      - ENABLE_ACCOUNT_SIGNUP=true
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=chatwoot
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/chatwoot
      - PGVECTOR_EXTENSION=true
      - FORCE_SSL=false
    ports:
      - "3031:3000"
    networks:
      - chatwoot-network
    restart: always
    entrypoint: docker/entrypoints/rails.sh
    command: bundle exec rails s -p 3000 -b 0.0.0.0

networks:
  chatwoot-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
