version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    restart: always
    environment: &base-env
      - RAILS_ENV=production
      - NODE_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=superSecret
      - FRONTEND_URL=http://localhost:3031
      - INSTALLATION_ENV=docker
      - ENABLE_ACCOUNT_SIGNUP=true
      - FORCE_SSL=false
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/chatwoot
      - REDIS_URL=redis://redis:6379

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - 3031:3000
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis-data:/data

volumes:
  pg-data:
  redis-data:
